### PR TITLE
Add position call afterRender to ensure position after render

### LINKED ISSUE #6: Tether loaded in incorrect place in 2.0.0-canary
Ember Version: 2.0.0-canary+4b74503e
    Ember Data Version: 2.0.0+canary.2b361f9837
    Ember Tether Version: 0.1.3

In the `didInsertElement` hook the tethered element is loaded in the incorrect place. 

These are the settings being used:

    offset: '10px 45px',
    attachment: 'top right',
    targetAttachment: 'top right',

This screenshot shows the positioning that I'm experiencing:

screen shot 2015-06-19 at 2 08 25 pm

If I add the following to the `didRender` hook it correctly repositions:

    this.removeTether(this._tether);
    this.addTether();

Below is a screenshot of the position after adding this workaround:

screen shot 2015-06-19 at 2 06 52 pm

I'm not sure how else to assist with this and couldn't spend any more time investigating so I thought I could at least open an issue.

### PR DESCRIPTION
**Pull request by kmiyashiro**
Fixes #6 

Unfortunately, I was not able to reproduce this in the dummy app. Since it occurs consistently in my app, I've tried these things in both my app and the dummy app:

* Removing all CSS
* Rendering conditionally and unconditionally via HTMLBars
* Nesting the tether or the target in components, other elements, etc
* Different variations of box model manipulations (min-width, padding, overflow, etc)

### CODE REVIEW

**Comment by craigsketchley** [comment]
Any status updates on this PR? `ember-tether` is broken for me without it.

**Comment by kmiyashiro** [comment]
Looks like this is fixed in #25, verifying

**Comment by kmiyashiro** [comment]
yup, fixed

**Comment by chrislopresto** [comment]
Thanks @kmiyashiro. Somehow my eyes glossed over when I was looking for related issues/PRs to reference with #25. 

I also meant to thank @craigsketchley. Thanks!

**Pull request closed without merging**
