### PR TITLE
Import tether automatically

### LINKED ISSUE #55: Use in an addon
Previously #43 and #38 have touched on this issue, but I'm still unable to use `ember-tether` in an addon without requiring `ember-tether` in the app as well. 
https://github.com/dfreeman/ember-cli-node-assets/issues/1 indicates this is expected behavior and `peerDependencies` is the solution.

Ember-cli 2.16+ supports importing directly from `node_modules`, how do you feel about dropping support for `ember-cli` < 2.16 and importing `Tether` that way instead of relying on `ember-cli-node-assets`?

### PR DESCRIPTION
**Pull request by jrjohnson**
Using ember-auto-import to bring in tether solves issues with nested
addons.

Fixes #55 

@lukemelia - how about this solution, which maintains backwards compatibility and moves in the direction of the overall ember community?

### CODE REVIEW

**Comment by lukemelia** [comment]
Love it @jrjohnson. I'll merge once green.

**Comment by jrjohnson** [comment]
Ok, updates and rebase fixed tests @lukemelia all green now.

**Comment by jrjohnson** [comment]
I don't think I have npm publish permissions @lukemelia can I bug you one last time for a 2.0 release (with the breaking drop of node 4)?

**Comment by Turbo87** [comment]
@lukemelia any news on the release?  🙏

if you need help, feel free to give me the npm/GitHub permission and I'll get it out there  :)

**Comment by lukemelia** [comment]
Thanks, Toby! Welcome aboard!

**Comment by Turbo87** [comment]
muchas gracias! can you make sure to `npm owner add turbo87 ember-tether` so that I can also push the release on npm? :)

**Comment by lukemelia** [comment]
Should be done already. Let me know if not.

**Comment by Turbo87** [comment]
```
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/ember-tether - You do not have permission to publish "ember-tether". Are you logged in as the correct user?
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tbieniek/.npm/_logs/2020-04-15T16_37_39_866Z-debug.log
```

😢

**Comment by lukemelia** [comment]
Sorry! Try now.

**Comment by Turbo87** [comment]
```
$ npm publish ember-tether-2.0.0.tgz
npm notice 
npm notice package: ember-tether@2.0.0
npm notice === Tarball Contents === 
npm notice 3.0kB addon/components/ember-tether.js
npm notice 63B   app/components/ember-tether.js  
npm notice 90B   config/environment.js           
npm notice 71B   index.js                        
npm notice 1.9kB package.json                    
npm notice 7.2kB CHANGELOG.md                    
npm notice 1.1kB LICENSE.md                      
npm notice 3.3kB README.md                       
npm notice === Tarball Details === 
npm notice name:          ember-tether                            
npm notice version:       2.0.0                                   
npm notice package size:  5.5 kB                                  
npm notice unpacked size: 16.7 kB                                 
npm notice shasum:        4fcb88749e8c11d3795173e96e894089328005b4
npm notice integrity:     sha512-07QCzYE5VZsQ5[...]RdA9rOSoxcBJw==
npm notice total files:   8                                       
npm notice 
+ ember-tether@2.0.0
```

🎉

**Comment by lukemelia** [comment]
Thanks @Turbo87! 🙏

**Pull request merged**
