### PR TITLE
Import tether ourselves

### LINKED ISSUE #55: Use in an addon
Previously #43 and #38 have touched on this issue, but I'm still unable to use `ember-tether` in an addon without requiring `ember-tether` in the app as well. 
https://github.com/dfreeman/ember-cli-node-assets/issues/1 indicates this is expected behavior and `peerDependencies` is the solution.

Ember-cli 2.16+ supports importing directly from `node_modules`, how do you feel about dropping support for `ember-cli` < 2.16 and importing `Tether` that way instead of relying on `ember-cli-node-assets`?

### PR DESCRIPTION
**Pull request by jrjohnson**
`ember-cli-node-assets` doesn't work in a nested addon situation, instead
we can pull Tether into our /vendor tree and include it directly.

Fixes #55

### CODE REVIEW

**Comment by jrjohnson** [comment]
@lukemelia just a bump on this. If it isn't a good solution I can try something else.

**Comment by lukemelia** [comment]
Sorry for the delayed response, @jrjohnson. I would strongly prefer to keep this as an npm dep so that we can more effectively manage it, de-dupe it, etc.

**Comment by jrjohnson** [comment]
I'm not sure I understand that, I might just not know enough about NPM. This only changes the way tether is bundled into the vendor.js for apps. The dependency is still maintained in NPM in this project.

I'll try this again using `ember-auto-import` and see if that makes more sense.

**Comment by lukemelia** [comment]
@jrjohnson Ah, I misunderstood (and didn't read the code!). ember-auto-import would be preferable. If that doesn't work, the approach you have is acceptable.

**Pull request closed without merging**
