### PR TITLE
Update ember-try config to test 1.12 and 1.13.

### PR DESCRIPTION
**Pull request by rwjblue**
* Change default `bower.json` target to use 1.13.2.
* Add 1.12.1 to known scenarios and travis runs.

### CODE REVIEW

**Comment by rwjblue** [comment]
Requires #4 to pass on 1.13+.

**Comment by chrislopresto** [comment]
Merged #4 

Onward and such :sunrise_over_mountains:

**Comment by rwjblue** [comment]
Rebased!

**Comment by chrislopresto** [comment]
Rad.

**Pull request merged**
